var configs = new Configs({
	style: 'acorn',
	fsize: '1',
	spacing: '1.2',
	margin: '1',
	popupWidth: '400',
	popupHeight: '600',
	text: 'FFFFFF',
	background: 'FFFFFF',
	link: 'FFFFFF',
	wiktionaryapi: 'en.wiktionary.org',
	alternateapi: true,
	preserveCase: false,
	_anchor: '',
})
